### ISSUE TITLE
Heatmap

### ISSUE THREAD

**Issue by mtennekes** [edwindj/qbinplots#1]
`qbin_violinplot`
`qbin_heatplot`
...

**Comment by edwindj** [comment]
good idea, but two comments:

- since the data is split in 100 parts, there should be enough rows in the dataset. So for datasets < 1000 rows, these won't add much extra information
- computational one: for the `funq_plot` and `qbin_boxplot` there only need to be 6 numbers calculated for qbin: so for each variable there will be around nbin x 6 numbers (e.g. 600). 
For a heatplot there will be around nbin x nbin numbers (e.g. 10,000), which is doable, but seems a bit silly for datasets with nrows() < 10,000.

**Comment by edwindj** [comment]
Started implementing heatmap version

**Comment by mtennekes** [comment]
Great!

Your first argument also holds for box plots; 10 data points per bin is very low (also for table plots)

**Comment by edwindj** [comment]
I partially agree:

- you are of course completely right that boxplot is "just another way" of visualizing distribution and the qbin distributions are equal no matter what visualisation you use: few data points per bin gives a noisy distribution.
- I do think boxplots are visually more "stable" with noisy distributions, by their nature of summarizing a distribution to five robust numbers.

The `qbin_heatmap` are a valuable addition/complement to `qbin_boxplot` since they allow for more nuance.
